### PR TITLE
Found and fixed problem with parent segment having more than two children

### PR DESCRIPTION
**Pull request by solveignaess**
* fixed bug in code for computing axial currents in cell where more than two segments are connected to one parent
* added tests

### CODE REVIEW

**Comment by espenhgn** [comment]
Thanks. Something may have changed with TravisCI resulting in failure to build test environments. 

Edit: Oh, and in the future, perhaps don't continue working on branches with change sets already merged into LFPy ;)

Edit: Never mind the above comment; restarted jobs on Travis ran successfully.

**Review by torbjone — APPROVED** [review]
Everything seems good to me.

**Comment by espenhgn** [comment]
Thanks, now merged. @solveignaess , you can now delete your branch sib_fix remotely and locally.

**Comment by solveignaess** [comment]
Sorry about the old branch, Espen!=S Thought it looked weird, now I understand why.=)

**Pull request merged**
