### PR TITLE
Issue117 fixes

### PR DESCRIPTION
**Pull request by espenhgn**
Fixes Issue #117 locally. The problem was that the NetworkCell class definition sets a `netconlist` attribute supposed to contain NetCons for detecting somatic spikes, while the base Cell class already contains one such similarly named list used for NetCons used to activate regular Synapse instances. I renamed `NetworkCell.netconlist` to `NetworkCell.sd_netconlist`. I also added a test for this issue, and fixed some h5py deprecation warnings

### CODE REVIEW

**Comment by espenhgn** [comment]
Updated TravisCI build to use NEURON 7.7.0, as it appeared to use an outdated buffered version of the master branch.

**Comment by espenhgn** [comment]
@torbjone, seems fixed now. But Worst. Bug. Ever.

**Comment by espenhgn** [comment]
@torbjone can I merge this PR?

**Comment by torbjone** [comment]
Will look at it now, and let you know soon if it works.

**Comment by espenhgn** [comment]
> Will look at it now, and let you know soon if it works.

Fine. I tested all the standard examples and it seems fine.

**Comment by torbjone** [comment]
Solves the problem here, and looks good to me. Merge away :-)

**Comment by espenhgn** [comment]
> Solves the problem here, and looks good to me. Merge away :-)

Done!

**Pull request merged**
