### PR TITLE
semantic changes to network examples

### PR DESCRIPTION
**Pull request by espenhgn**

### CODE REVIEW

**Comment by espenhgn** [comment]
Since PR #120 & #117 fixed some issues with setting synaptic parameters and activation times, this meant that the example network required an update to its parameters. This is what the output looks like now: 
[figure_5.pdf](https://github.com/LFPy/LFPy/files/2906118/figure_5.pdf)

Due to differences in some synaptic parameters, it is probably not possible to get back the exact state that resulted earlier. Additional fine tuning could probably bring it closer, but I'm not sure if it is worth the effort.

**Comment by espenhgn** [comment]
Should add; the PR fixes some deprecated h5py and matplotlib codes, and supports Python3 as well. The Neurotools.parameters module has been swapped with a freestanding version that supports Python3.

@torbjone , can I just merge this?

**Comment by torbjone** [comment]
Go ahead and merge!

**Comment by espenhgn** [comment]
> Go ahead and merge!

Done!

**Pull request merged**
