### PR TITLE
Changed documentation style to numoydoc

### PR DESCRIPTION
**Pull request by torbjone**
I have started the transition to numpydoc (https://github.com/numpy/numpy/blob/master/doc/HOWTO_DOCUMENT.rst.txt). More work should be put into the documentation, but this is a start.

### CODE REVIEW

**Comment by espenhgn** [comment]
@torbjone Looks good but conflicts must be resolved, maybe because you used 'master' as base for edits? Also, I would suggest to continue implementing on a new branch ("numpydoc") and make sure that this working branch has all upstream changes in "dev" now merged into it. Then, unittests should hopefully run automatically with Travis CI, and manually with 
`nosetests-2.7 --with-coverage --cover-package=LFPy`

So the workflow would be like
```
git checkout master #since you are apparently working on 'master' 
git checkout dev # get upstream changes 
git pull origin dev
git checkout master
git branch -b numpydoc
git merge dev
# fix conflicts and commit
git push torbjone numpydoc
# amend PR
```

**Comment by torbjone** [comment]
I thought I had resolved this since I merged with LFPy/dev locally forst, but it appears not. I probably made some new changes that caused conflict in my attempt to merge. Will try again :-)

**Comment by torbjone** [comment]
I have made a new and hopefully fixed pull request.

**Comment by espenhgn** [comment]
@torbjone These different merges I did probably conflicted with what you did then.

**Pull request closed without merging**
