### PR TITLE
Got NaN in EEG calculation due to numerical round-off error, causing …

### PR DESCRIPTION
**Pull request by torbjone**
…cos_phi to be slightly outside valid range of [-1,1]. Fixed by adding small number.

### CODE REVIEW

**Review by espenhgn — CHANGES_REQUESTED** [review]
I'd prefer if we simply state:
'''
        cos_phi[np.where(cos_phi > 1.0)] = 1.
        cos_phi[np.where(cos_phi < -1.0)] = -1.
'''

**Comment by espenhgn** [comment]
Would it be possible to also include a test for this issue? it would be good to understand how these numerical round off errors can occur.

**Comment by torbjone** [comment]
The reason I wrote it like I did, is that I only wanted my solution to fix potential round-off errors, and not any other hypothetical error which might make cos_phi go far outside the valid range, but I can see how you suggestion might be better.

I don't have time to investigate in detail right now, but in my case, both the nominator and denominator of the line
        cos_phi = np.dot(rxy, x.T) / denominator
were big and essentially identical numbers. My guess is that a tiny round-off happened in the line:
        denominator = np.dot(np.linalg.norm(rxy, axis=1).reshape(len(rxy),1),
                             np.linalg.norm(x, axis=1).reshape(1, len(x)))

**Comment by espenhgn** [comment]
Hmm, the code computing the denominator is also pretty weird, in particular:
denominator[np.where(denominator == 0)] = 1e-12

Actually, I don't know why computing this azimuthal angle should require that much code (as in this whole function calc_phi).

**Comment by torbjone** [comment]
Suggested changes have been made.

**Comment by espenhgn** [comment]
Would it be alright to get @solveignaess input on this before accepting a hack to a function that already looks hacky? I don't quite understand what this function is supposed to do. The docstring says:
```

        Return azimuthal angle between x-axis and contact point locations(s)
        Parameters
        ----------
        p_tan : ndarray, dtype=float
            Shape (n_contacts, n_timesteps) array containing
            tangential component of current dipole moment in units of (nA*µm)
        Returns
        -------
        phi : ndarray, dtype=float
            Shape (n_contacts, n_timesteps) array containing azimuthal angle
            in units of (radians) between x-axis vector(s) and projection of
            contact point location vector(s) rxyz into xy-plane.
            z-axis is defined in the direction of rzloc.
            y-axis is defined in the direction of p (orthogonal to rzloc).
            x-axis is defined as cross product between p and rzloc (x).
```

**Comment by torbjone** [comment]
OK, we leave this to Solveig comes back then.

**Comment by espenhgn** [comment]
Fine with me.

**Pull request closed without merging**
