### PR TITLE
Adding network functionality to LFPy

### PR DESCRIPTION
**Pull request by espenhgn**
Addresses Issue #8. Adds new classes and methods to LFPy for computing extracellular potentials and current-dipole moments from networks and populations of multicompartment neurons

New classes:
- `LFPy.Network`: topmost class for creating populations of cells of different types plus methods for creating connectivity (random) and connections across different compute ranks
- `LFPy.NetworkPopulation`: class representation for different network populations that uses the same network-cell specification
- `LFPy.NetworkCell`: inherited from `LFPy.TemplateCell` and adds some functionality for spike detection and communication over NetCon devices

Example files:
- `examples/example_network/BallAndStick.hoc`: ball and stick model neuron with passive dendrite and HH in soma
- `examples/example_network/BallAndStickTemplate.py`: corresponding NEURON template file
- `examples/example_network/example_NetworkCell.py`: example script for testing `LFPy.TemplateCell` class
- `examples/example_network/example_Network.py`: example script for creating 2 interconnected populations (E and I) of ball and stick neurons connected by excitatory and inhibitory synapses

### CODE REVIEW

**Comment by espenhgn** [comment]
@torbjone Can I merge this?

**Comment by torbjone** [comment]
I haven't looked at the latest changes, but you can either just go ahead, or wait for an hour or two while I look at it, up to you :-)

**Comment by torbjone** [comment]
This works perfectly well on my end, and I have no immediate concern. I suggest you do the merging, and I will let you know if I stumble upon any issues while I work on it.

**Review by torbjone — APPROVED** [review]
Go ahead!

**Comment by espenhgn** [comment]
Done!

**Pull request merged**
