### PR TITLE
Get rid of package dependency on `mpi4py`

### LINKED ISSUE #429: Make `mpi4py` an optional dependency
Hi @espenhgn 

**Is your feature request related to a problem? Please describe.**
Would it be possible to make `mpi4py` an optuional requirement, since it's only used in the network simulations?
We are integrating LFPy as a possible backend for BluePyOpt, and it seems like an unnecessary dependency since we only use single neuron models. See https://github.com/BlueBrain/BluePyOpt/pull/385#issuecomment-1193726658

**Describe the solution you'd like**
Make `mpi4py` optional in `network.py`.

Something like:
```
try:
    from mpi4py import MPI
    HAVE_MPI = True
except ImportError:
    HAVE_MPI = False
```

and then `asser HAVE_MPI` in the function and condinionally define the `def ReduceStructArray(sendbuf, op=MPI.SUM)` function:
```
if HAVE_MPI:
    def ReduceStructArray(sendbuf, op=MPI.SUM):
        ....
```

**Describe alternatives you've considered**
Making `mpi4py` a weak dependency with lazy import. You could also have a specific extra_requires `mpi4py`: `pip install LFPy[mpi]`

Let us know what you think!

### PR DESCRIPTION
**Pull request by espenhgn**
Closes #429, by removing the package dependency on mpi4py altogether. 
This PR supersedes #430.

### CODE REVIEW

**Comment by espenhgn** [comment]
Hi @alejoe91, 
Can you please test if this PR/branch works for your purpose? 
It does no longer require `mpi4py` as an install dependency for LFPy, but can still be (optionally) used to let NEURON know that it is in a parallel setting by importing `MPI` before `import neuron` (as is the usual behavior with LFPy):
```bash
(lfpy) espenhagen@Espens-MBP example_network % mpirun python -c "import LFPy"
(lfpy) espenhagen@Espens-MBP example_network % python -c "import LFPy"                                     
(lfpy) espenhagen@Espens-MBP example_network % python -c "from mpi4py import MPI; import LFPy"
numprocs=1
(lfpy) espenhagen@Espens-MBP example_network % mpirun python -c "import LFPy" 
(lfpy) espenhagen@Espens-MBP example_network % mpirun -np 4 python -c "from mpi4py import MPI; import LFPy"
numprocs=4
(lfpy) espenhagen@Espens-MBP example_network % mpirun -np 4 python -c "import LFPy; from mpi4py import MPI"
```

**Review by alejoe91 — APPROVED** [review]
@espenhgn thank you!!! It's working on our tests too!! :)

**Comment by espenhgn** [comment]
@alejoe91, thanks for testing! Will merge.

**Comment by wvangeit** [comment]
Hi @espenhgn 
Would it be possible to release a version of LFPy on PyPi fairly quickly (that includes this PR)?
I merged the LFPy integration into BluePyOpt (https://github.com/BlueBrain/BluePyOpt). We were using a package dependency pointing to the master of the LFPy repo. Unfortunately PyPi doesn't allow such dependencies, so we're blocked for a new BluePyOpt release until there is a new LFPy package. 
(https://github.com/BlueBrain/BluePyOpt/actions/runs/3646835850/jobs/6158794949)

Thank you

**Comment by espenhgn** [comment]
Hi @wvangeit, 
Thanks for the heads up. Sure, we should not prevent future releases of BluePyOpt across the usual channels. 
I think on our end the only minor issue is that the branch master is now effectively the LFPy-2.3dev branch which will ultimately break some backward compatibility with the LFPy-2.2.x releases. 

Can check what makes more sense, either adding this fix into the maintenance branch https://github.com/LFPy/LFPy/tree/maintenance/2.2.x, or making a release 2.2.7 from the current master. 
It's probably a good idea to release a version of LFPy that's compatible with the recently released Python 3.11.x and NEURON 8.2.x anyway. 

Opened https://github.com/LFPy/LFPy/issues/438

**Comment by espenhgn** [comment]
Hi again, @wvangeit. LFPy-2.3 is now released on [GitHub](https://github.com/LFPy/LFPy/releases/tag/v2.3) and available on [PyPI.org](https://pypi.org/project/LFPy/). Let me know if you encounter any issues!

**Comment by wvangeit** [comment]
Thank you very much @espenhgn ! We'll run our tests again.

**Pull request merged**
